"""add_volunteer_profile_fields

Revision ID: 66f614c3595d
Revises: 
Create Date: 2026-08-15 01:08:55.800743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66f614c3595d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_workspace_caches_resource_id'), table_name='ai_workspace_caches')
    op.drop_table('ai_workspace_caches')
    op.drop_index(op.f('idx_ai_chunk_resource'), table_name='ai_document_chunks')
    op.drop_index(op.f('ix_ai_document_chunks_resource_id'), table_name='ai_document_chunks')
    op.drop_table('ai_document_chunks')
    op.drop_index(op.f('idx_ai_doc_hash'), table_name='ai_documents')
    op.drop_index(op.f('idx_ai_doc_resource'), table_name='ai_documents')
    op.drop_index(op.f('ix_ai_documents_resource_id'), table_name='ai_documents')
    op.drop_table('ai_documents')
    op.drop_index(op.f('ix_ai_question_banks_resource_id'), table_name='ai_question_banks')
    op.drop_table('ai_question_banks')
    op.drop_index(op.f('idx_student_progress_user_resource'), table_name='ai_student_progress')
    op.drop_index(op.f('ix_ai_student_progress_resource_id'), table_name='ai_student_progress')
    op.drop_table('ai_student_progress')
    op.alter_column('events', 'mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'online'::character varying"))
    op.alter_column('events', 'verification_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('events', 'event_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('events', 'is_free',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('resources', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'samidha'::character varying"))
    op.alter_column('resources', 'rating_sum',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('resources', 'rating_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('resources', 'rating_avg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.create_index('idx_created_at', 'resources', ['created_at'], unique=False)
    op.create_index('idx_resource_filter', 'resources', ['target_class', 'subject_name', 'resource_category'], unique=False)
    op.create_index('idx_resource_source', 'resources', ['verification_status', 'created_at'], unique=False)
    op.create_index('idx_source_class', 'resources', ['source_type', 'target_class'], unique=False)
    op.create_index('idx_source_class_subject', 'resources', ['source_type', 'target_class', 'subject_name'], unique=False)
    op.create_index(op.f('ix_resources_resource_category'), 'resources', ['resource_category'], unique=False)
    op.create_index(op.f('ix_resources_source_type'), 'resources', ['source_type'], unique=False)
    op.create_index(op.f('ix_resources_subject_name'), 'resources', ['subject_name'], unique=False)
    op.create_index(op.f('ix_resources_target_class'), 'resources', ['target_class'], unique=False)
    op.alter_column('scraper_jobs', 'total_subjects_found',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('scraper_jobs', 'total_chapters_found',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('scraper_jobs', 'scraped_success_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('scraper_jobs', 'scraped_failed_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('scraper_jobs', 'duration_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('scraper_jobs', 'telemetry_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('scraper_jobs', 'scraped_sheet',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('volunteer_profiles', sa.Column('academic_year', sa.String(length=50), nullable=True))
    op.add_column('volunteer_profiles', sa.Column('whatsapp_number', sa.String(length=20), nullable=True))
    op.add_column('volunteer_profiles', sa.Column('assigned_role', sa.String(length=255), nullable=True))
    op.add_column('volunteer_profiles', sa.Column('is_featured_mentor', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('volunteer_profiles', 'approval_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('volunteer_profiles', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('volunteer_profiles_approved_by_fkey'), 'volunteer_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'volunteer_profiles', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteer_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('volunteer_profiles_approved_by_fkey'), 'volunteer_profiles', 'users', ['approved_by'], ['id'])
    op.alter_column('volunteer_profiles', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('volunteer_profiles', 'approval_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_column('volunteer_profiles', 'is_featured_mentor')
    op.drop_column('volunteer_profiles', 'assigned_role')
    op.drop_column('volunteer_profiles', 'whatsapp_number')
    op.drop_column('volunteer_profiles', 'academic_year')
    op.alter_column('scraper_jobs', 'scraped_sheet',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('scraper_jobs', 'telemetry_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('scraper_jobs', 'duration_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('scraper_jobs', 'scraped_failed_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('scraper_jobs', 'scraped_success_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('scraper_jobs', 'total_chapters_found',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('scraper_jobs', 'total_subjects_found',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_resources_target_class'), table_name='resources')
    op.drop_index(op.f('ix_resources_subject_name'), table_name='resources')
    op.drop_index(op.f('ix_resources_source_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_category'), table_name='resources')
    op.drop_index('idx_source_class_subject', table_name='resources')
    op.drop_index('idx_source_class', table_name='resources')
    op.drop_index('idx_resource_source', table_name='resources')
    op.drop_index('idx_resource_filter', table_name='resources')
    op.drop_index('idx_created_at', table_name='resources')
    op.alter_column('resources', 'rating_avg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('resources', 'rating_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('resources', 'rating_sum',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('resources', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'samidha'::character varying"))
    op.alter_column('events', 'is_free',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('events', 'event_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('events', 'verification_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('events', 'mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'online'::character varying"))
    op.create_table('ai_student_progress',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quizzes_taken', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_quiz_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weak_topics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('mastered_flashcards', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ai_student_progress_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_student_progress_pkey'))
    )
    op.create_index(op.f('ix_ai_student_progress_resource_id'), 'ai_student_progress', ['resource_id'], unique=False)
    op.create_index(op.f('idx_student_progress_user_resource'), 'ai_student_progress', ['user_id', 'resource_id'], unique=True)
    op.create_table('ai_question_banks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('questions_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_question_banks_pkey'))
    )
    op.create_index(op.f('ix_ai_question_banks_resource_id'), 'ai_question_banks', ['resource_id'], unique=False)
    op.create_table('ai_documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('total_pages', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_documents_pkey')),
    sa.UniqueConstraint('file_hash', name=op.f('ai_documents_file_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_ai_documents_resource_id'), 'ai_documents', ['resource_id'], unique=False)
    op.create_index(op.f('idx_ai_doc_resource'), 'ai_documents', ['resource_id'], unique=False)
    op.create_index(op.f('idx_ai_doc_hash'), 'ai_documents', ['file_hash'], unique=True)
    op.create_table('ai_document_chunks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['ai_documents.id'], name=op.f('ai_document_chunks_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_document_chunks_pkey'))
    )
    op.create_index(op.f('ix_ai_document_chunks_resource_id'), 'ai_document_chunks', ['resource_id'], unique=False)
    op.create_index(op.f('idx_ai_chunk_resource'), 'ai_document_chunks', ['resource_id'], unique=False)
    op.create_table('ai_workspace_caches',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_workspace_caches_pkey'))
    )
    op.create_index(op.f('ix_ai_workspace_caches_resource_id'), 'ai_workspace_caches', ['resource_id'], unique=True)
    # ### end Alembic commands ###
